# This rule is not used by the project timesync-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the sync.example.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: timesync-operator
    app.kubernetes.io/managed-by: kustomize
  name: timesyncpolicy-editor-role
rules:
- apiGroups:
  - sync.example.com
  resources:
  - timesyncpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sync.example.com
  resources:
  - timesyncpolicies/status
  verbs:
  - get
