apiVersion: sync.example.com/v1alpha1
kind: TimeSyncPolicy
metadata:
  labels:
    app.kubernetes.io/name: timesync-operator
    app.kubernetes.io/managed-by: kustomize
  name: timesyncpolicy-sample
spec:
  # TODO(user): Add fields here
